        !COMPILER-GENERATED INTERFACE MODULE: Wed May 02 20:59:27 2018
        MODULE MOORINGLINE__genmod
          INTERFACE 
            SUBROUTINE MOORINGLINE
            END SUBROUTINE MOORINGLINE
          END INTERFACE 
        END MODULE MOORINGLINE__genmod
